unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g mouse on
set -g prefix C-s
set -g base-index 1
set -g default-terminal "tmux-256color"

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind | split-window -h -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"

# Toggle lazygit in a floating popup (closes automatically when lazygit exits)
bind g display-popup -d "#{pane_current_path}" -w 90% -h 90% -E "lazygit"

set-option -g status-position top

# use vim-style keys to resize panes
# bind -r h resize-pane -L 5
# bind -r l resize-pane -R 5
# bind -r j resize-pane -D 2
# bind -r k resize-pane -U 2

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_current_text "#W"

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

set -g @resurrect-dir '~/.tmux/resurrect'
set -g @resurrect-save 'S'
set -g @resurrect-restore 'R'
set -g @continuum-restore 'on'

set -gq allow-passthrough on
set -g visual-activity off

run '~/.tmux/plugins/tmux-resurrect/resurrect.tmux'
run '~/.tmux/plugins/tpm/tpm'
